
##Musics
##Las músicas comentadas, no se usaron en está versión del juego, no las descomentes ya que no están disponibles aún

define audio.m1 = "audio/Welcome.opus"
#define audio.end = "audio/Colorful_Canvas_Remix.opus"
define audio.a1 = "audio/Good_Day.opus"
define audio.a2 = "audio/Relax.opus"
define audio.a3 = "audio/Think.opus"
define audio.a4 = "audio/Euphoria.opus"
define audio.a5 = "audio/DeepAmbience.ogg"
#define audio.a6 = "audio/Brika_Demons.opus"
define audio.a7 = "audio/Hikara.opus"
#define audio.a8 = "audio/Happy.opus"
define audio.a9 = "audio/Sad.opus"
#define audio.a9 = "audio/Reflexion.opus"

##SFX
##Los sonidos comentados, no se usaron en está versión del juego, no los descomentes ya que no están disponibles aún

define audio.pageflip = "audio/sfx/page.ogg"
define audio.dripper = "audio/sfx/Dripper.ogg"
define audio.punch = "audio/sfx/punch.ogg"
define audio.knock = "audio/sfx/knock.ogg"
define audio.alarm = "audio/sfx/alarm.ogg"
define audio.yumi_cry = "audio/sfx/yumi_cry.ogg"
define audio.doorbell = "audio/sfx/doorbell.ogg"
define audio.door2a = "audio/sfx/Door2a.ogg"
define audio.door2b = "audio/sfx/Door2b.ogg"
define audio.door2c = "audio/sfx/Door2c.ogg"
define audio.dooropen = "audio/sfx/dooropen.ogg"
define audio.doorunlock = "audio/sfx/doorunlock.ogg"
define audio.doorcreak1 = "audio/sfx/doorcreak1.ogg"
define audio.doorcreak2 = "audio/sfx/doorcreak2.ogg"
define audio.doorcreak3 = "audio/sfx/doorcreak3.ogg"
define audio.doorcreak4 = "audio/sfx/doorcreak4.ogg"
define audio.fall = "audio/sfx/fall.ogg"
define audio.fall2 = "audio/sfx/fall2.ogg"
#define audio.flashlight = "audio/sfx/Flashlight.ogg"
define audio.schoolbell = "audio/sfx/schoolbell.ogg"
define audio.stopper = "audio/sfx/Stopper.ogg"
#define audio.shower = "audio/sfx/shower.ogg"
#define audio.storebell = "audio/sfx/storebell.ogg"
#define audio.sms = "audio/sfx/sms.ogg"
#define audio.kiss = "audio/sfx/kissing.ogg"
#define audio.heartbeat = "audio/sfx/heartbeat.ogg"